name: loagapps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Noto_Sans/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
